---
- hosts: all
  become: true

  tasks:
    - name: Installing requirements
      apt:
        name: "{{ packages }}"
        update_cache: yes
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
    - name: Adding Docker's GPG Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Adding Docker Repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present
    - name: Installing docker-ce, docker-cli, containerd.io
      apt:
        name: "{{ items }}"
        update_cache: yes
      vars:
        items:
          - docker-ce
          - docker-ce-cli
          - containerd.io
    - name: Installing docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.24.0/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 0755
